/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import com.itextpdf.text.DocumentException;
import java.io.FileNotFoundException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DEETH
 */
public class Admin extends javax.swing.JFrame {

    public Admin() {
        setTitle("Admin Page");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenusalaryreport = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jColorChooser1 = new javax.swing.JColorChooser();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        button1 = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuview = new javax.swing.JMenu();
        jMenuItememployees = new javax.swing.JMenuItem();
        jMenuaddnew = new javax.swing.JMenu();
        jMenunewemployee = new javax.swing.JMenuItem();
        jMenunewproject = new javax.swing.JMenuItem();
        jMenunewleave = new javax.swing.JMenuItem();
        jMenuItemPerformance = new javax.swing.JMenuItem();
        jMenuItemAwards = new javax.swing.JMenuItem();
        jMenuItemattendance = new javax.swing.JMenuItem();
        jMenuItemDesignation = new javax.swing.JMenuItem();
        jMenuItemSep = new javax.swing.JMenuItem();
        jMenureports = new javax.swing.JMenu();
        jMenuattendancereport = new javax.swing.JMenuItem();
        jMenuseprpt = new javax.swing.JMenuItem();
        jMenuleaverpt = new javax.swing.JMenuItem();
        outstandingPerformers = new javax.swing.JMenuItem();
        projectAss = new javax.swing.JMenuItem();
        hired = new javax.swing.JMenuItem();
        jMenurecruitment = new javax.swing.JMenu();
        jMenuItemhiring = new javax.swing.JMenuItem();
        jMenumyacc = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuabt = new javax.swing.JMenu();
        jMenuItemcompany = new javax.swing.JMenuItem();

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem1.setText("jMenuItem1");

        jMenusalaryreport.setText("jMenuItem5");

        jMenuItem5.setText("jMenuItem5");

        jMenuItem6.setText("jMenuItem6");

        jMenuItem7.setText("jMenuItem7");

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar2.add(jMenu2);

        button1.setLabel("button1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\MOVIES\\PICS\\8.jpg")); // NOI18N
        jLabel1.setText("WELCOME!!!");

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("WELCOME!");

        jMenuview.setText("View");
        jMenuview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuviewActionPerformed(evt);
            }
        });

        jMenuItememployees.setText("Employees Information");
        jMenuItememployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItememployeesActionPerformed(evt);
            }
        });
        jMenuview.add(jMenuItememployees);

        jMenuBar1.add(jMenuview);

        jMenuaddnew.setText("AddNew");

        jMenunewemployee.setText("Employee");
        jMenunewemployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenunewemployeeActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenunewemployee);

        jMenunewproject.setText("Project");
        jMenunewproject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenunewprojectActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenunewproject);

        jMenunewleave.setText("Leave");
        jMenunewleave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenunewleaveActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenunewleave);

        jMenuItemPerformance.setText("Employee Performamce");
        jMenuItemPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPerformanceActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenuItemPerformance);

        jMenuItemAwards.setText("Awards");
        jMenuItemAwards.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAwardsActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenuItemAwards);

        jMenuItemattendance.setText("Attendance");
        jMenuItemattendance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemattendanceActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenuItemattendance);

        jMenuItemDesignation.setText("Designation");
        jMenuItemDesignation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemDesignationActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenuItemDesignation);

        jMenuItemSep.setText("Employee Separation");
        jMenuItemSep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSepActionPerformed(evt);
            }
        });
        jMenuaddnew.add(jMenuItemSep);

        jMenuBar1.add(jMenuaddnew);

        jMenureports.setText("Reports");

        jMenuattendancereport.setText("Absenteeism Report");
        jMenuattendancereport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuattendancereportActionPerformed(evt);
            }
        });
        jMenureports.add(jMenuattendancereport);

        jMenuseprpt.setText("Involuntary Employee Separations Report");
        jMenuseprpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuseprptActionPerformed(evt);
            }
        });
        jMenureports.add(jMenuseprpt);

        jMenuleaverpt.setText("Approved Leaves Report");
        jMenuleaverpt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuleaverptActionPerformed(evt);
            }
        });
        jMenureports.add(jMenuleaverpt);

        outstandingPerformers.setText("Outstanding Performers Report");
        outstandingPerformers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outstandingPerformersActionPerformed(evt);
            }
        });
        jMenureports.add(outstandingPerformers);

        projectAss.setText("Project Assignment Report");
        projectAss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectAssActionPerformed(evt);
            }
        });
        jMenureports.add(projectAss);

        hired.setText("Hired Candidates Report");
        hired.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiredActionPerformed(evt);
            }
        });
        jMenureports.add(hired);

        jMenuBar1.add(jMenureports);

        jMenurecruitment.setText("Recruitment");

        jMenuItemhiring.setText("Hiring Management");
        jMenuItemhiring.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemhiringActionPerformed(evt);
            }
        });
        jMenurecruitment.add(jMenuItemhiring);

        jMenuBar1.add(jMenurecruitment);

        jMenumyacc.setText("MyAccount");

        jMenuItemLogout.setText("Logout");
        jMenuItemLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLogoutActionPerformed(evt);
            }
        });
        jMenumyacc.add(jMenuItemLogout);

        jMenuBar1.add(jMenumyacc);

        jMenuabt.setText("AboutUs");

        jMenuItemcompany.setText("Company Details");
        jMenuItemcompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemcompanyActionPerformed(evt);
            }
        });
        jMenuabt.add(jMenuItemcompany);

        jMenuBar1.add(jMenuabt);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenunewemployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenunewemployeeActionPerformed
        // TODO add your handling code here:
        
        NewEmployee employee = new NewEmployee("New Employee Form");
        employee.setVisible(true);

    }//GEN-LAST:event_jMenunewemployeeActionPerformed

    private void jMenunewprojectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenunewprojectActionPerformed
        // TODO add your handling code here:
        NewProject project = new NewProject("New Project Form");
        project.setVisible(true);
    }//GEN-LAST:event_jMenunewprojectActionPerformed

    private void jMenunewleaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenunewleaveActionPerformed
        // TODO add your handling code here:
        LeaveForm leave = new LeaveForm("Leave Form");
        leave.setVisible(true);
    }//GEN-LAST:event_jMenunewleaveActionPerformed

    private void jMenuviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuviewActionPerformed
       
    }//GEN-LAST:event_jMenuviewActionPerformed

    private void jMenuItememployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItememployeesActionPerformed
        // TODO add your handling code here:
       
        try {
            AllEmployees all = new AllEmployees();
            all.Main();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (DocumentException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItememployeesActionPerformed

    private void jMenuItemDesignationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDesignationActionPerformed
        // TODO add your handling code here:
        Desgnation des = new Desgnation();
        des.Main();
    }//GEN-LAST:event_jMenuItemDesignationActionPerformed

    private void jMenuItemhiringActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemhiringActionPerformed
        // TODO add your handling code here:
        Hirirng hire = new Hirirng();
        hire.Main();
    }//GEN-LAST:event_jMenuItemhiringActionPerformed

    private void jMenuItemPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPerformanceActionPerformed
        // TODO add your handling code here:
        Performance p = new Performance();
        p.Main();
    }//GEN-LAST:event_jMenuItemPerformanceActionPerformed

    private void jMenuItemAwardsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAwardsActionPerformed
        // TODO add your handling code here:
        Awards award = new Awards();
        award.Main();
    }//GEN-LAST:event_jMenuItemAwardsActionPerformed

    private void jMenuItemattendanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemattendanceActionPerformed
        // TODO add your handling code here:
        Attendance attend = new Attendance();
        attend.Main();
    }//GEN-LAST:event_jMenuItemattendanceActionPerformed

    private void jMenuItemSepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSepActionPerformed
        // TODO add your handling code here:
        Separation sep = new Separation();
        sep.Main();
    }//GEN-LAST:event_jMenuItemSepActionPerformed

    private void jMenuItemLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLogoutActionPerformed
        // TODO add your handling code here:
    int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
    if (option == JOptionPane.YES_OPTION) {
        dispose(); // close the current window
        System.exit(0); // exit the applicatio
    }
    }//GEN-LAST:event_jMenuItemLogoutActionPerformed

    private void jMenuattendancereportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuattendancereportActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeAttendace att = new EmployeeAttendace();
            att.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuattendancereportActionPerformed

    private void jMenuseprptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuseprptActionPerformed
        try {
            // TODO add your handling code here:
            EmployeeSeparation sep= new EmployeeSeparation();
            sep.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuseprptActionPerformed

    private void jMenuleaverptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuleaverptActionPerformed
        try {
            // TODO add your handling code here:
            ApprovedLeave app = new ApprovedLeave();
            app.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuleaverptActionPerformed

    private void outstandingPerformersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outstandingPerformersActionPerformed
        try {
            // TODO add your handling code here:
            OutstandingPerformers per = new OutstandingPerformers();
            per.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_outstandingPerformersActionPerformed

    private void projectAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectAssActionPerformed
        try {
            // TODO add your handling code here:
            ProjectAssignment prj = new ProjectAssignment();
            prj.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_projectAssActionPerformed

    private void jMenuItemcompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemcompanyActionPerformed
        // TODO add your handling code here:
        AboutUs us = new AboutUs();
        us.Main();
    }//GEN-LAST:event_jMenuItemcompanyActionPerformed

    private void hiredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiredActionPerformed
        // TODO add your handling code here:
        HiredCandidates hired = new HiredCandidates();
        try {
            hired.Main();
        } catch (FileNotFoundException | DocumentException | SQLException ex) {
            Logger.getLogger(Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_hiredActionPerformed

   
    public void Main() {
  
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Admin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JMenuItem hired;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItemAwards;
    private javax.swing.JMenuItem jMenuItemDesignation;
    private javax.swing.JMenuItem jMenuItemLogout;
    private javax.swing.JMenuItem jMenuItemPerformance;
    private javax.swing.JMenuItem jMenuItemSep;
    private javax.swing.JMenuItem jMenuItemattendance;
    private javax.swing.JMenuItem jMenuItemcompany;
    private javax.swing.JMenuItem jMenuItememployees;
    private javax.swing.JMenuItem jMenuItemhiring;
    private javax.swing.JMenu jMenuabt;
    private javax.swing.JMenu jMenuaddnew;
    private javax.swing.JMenuItem jMenuattendancereport;
    private javax.swing.JMenuItem jMenuleaverpt;
    private javax.swing.JMenu jMenumyacc;
    private javax.swing.JMenuItem jMenunewemployee;
    private javax.swing.JMenuItem jMenunewleave;
    private javax.swing.JMenuItem jMenunewproject;
    private javax.swing.JMenu jMenurecruitment;
    private javax.swing.JMenu jMenureports;
    private javax.swing.JMenuItem jMenusalaryreport;
    private javax.swing.JMenuItem jMenuseprpt;
    private javax.swing.JMenu jMenuview;
    private javax.swing.JMenuItem outstandingPerformers;
    private javax.swing.JMenuItem projectAss;
    // End of variables declaration//GEN-END:variables

    private void NewEmployee(String new_Employee) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
