/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JTextField;

/**
 *
 * @author DEETH
 */
public class Desgnation extends javax.swing.JFrame {
    Connection con;
    PreparedStatement Statement;
    Statement st;
    String cs;
    String user;
    String password;
    String query;
    ResultSet rset;
    String records;
    
    String s1;
    String s2;
    String s3;
        

    /**
     * Creates new form Desgnation
     */
    public Desgnation() {
        setTitle("Work Position");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtrptmanager = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        btnsave = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Employee Designations");

        jLabel2.setText("ID:");

        jLabel4.setText("Postion:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Director", "Secretary", "Accountant", "Others" }));

        btnsave.setBackground(new java.awt.Color(0, 255, 255));
        btnsave.setText("SAVE");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btnupdate.setText("UPDATE");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jLabel5.setText("Reporting Manager:");

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setText("PREVIOUS");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(115, 115, 115)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnupdate)
                            .addComponent(btnDelete))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                            .addComponent(txtrptmanager, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(117, 117, 117))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btnFind))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(btnsave)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(34, 34, 34))))
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4)))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtrptmanager, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnupdate)
                    .addComponent(btnsave, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnPrev))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        s2 =jComboBox1.getSelectedItem().toString();
        s3 = txtrptmanager.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query="INSERT INTO `designationinfo`(`ID`, `DesignationName`, `ReportingManager`) VALUES ('" +s1+"','" +s2+"','" +s3+"');";
            st.executeUpdate(query);
            
            JOptionPane.showMessageDialog(null,"Recrod Saved");
            st.close();
            con.close();}
        
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
                System.out.println(ex);
        }   
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        s2 =jComboBox1.getSelectedItem().toString();
        s3 = txtrptmanager.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "UPDATE designationinfo SET DesignationName = '" +s2+ "', ReportingManager  = '" +s3+ "'  WHERE ID ='"+s1+"'";
            int updated = st.executeUpdate(query);
            if (updated==1){
                JOptionPane.showMessageDialog(null, "Record Updated");
            }
            rset.close();
            st.close();
            con.close();
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
               
        int answer = JOptionPane.showConfirmDialog(this,"Are you sure You want to delete This Record?" ,"Confirm",JOptionPane.YES_NO_OPTION);
       
       if(answer == YES_OPTION){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
                 st = con.createStatement();
                 query = "DELETE FROM designationinfo WHERE ID = '" +s1+"'";
                 st.executeUpdate(query);
                 
                 txtid.requestFocus();
                 
                 if(st.executeUpdate(query)==0){
                     JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Deleted");
                 }else{JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Doesnot Exist");}
                 }
                catch (SQLException | ClassNotFoundException ex){
                }
           
           finally{
               if(st !=null){
                   try {
                       st.close();
                   } catch (SQLException ex) {
                       Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
                   }
}
               if(con !=null){
                   try {
                       con.close();
                   } catch (SQLException ex) {
                       Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }

               }
           
       }
       else if (answer == NO_OPTION){
                   txtid.requestFocus();}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "SELECT * FROM designationinfo WHERE ID = '"+s1 + "'";
           
            rset = st.executeQuery(query);
            if(rset.next()){
            
            txtid.setText(rset.getString("ID"));
            jComboBox1.setSelectedItem(rset.getString("DesignationName"));
            txtrptmanager.setText(rset.getString("ReportingManager"));
            
            
            
            JOptionPane.showMessageDialog(null,"Record found");}
            else{
                JOptionPane.showMessageDialog(null,"Record Not found");
            rset.close();
            st.close();
            con.close();}
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
            
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM designationinfo");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.next()){
                            txtid.setText(rset.getString("ID"));
                            jComboBox1.setSelectedItem(rset.getString("DesignationName"));
                            txtrptmanager.setText(rset.getString("ReportingManager"));
            
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
         s1=txtid.getText();
            
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM designationinfo");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.previous()){
                            txtid.setText(rset.getString("ID"));
                            jComboBox1.setSelectedItem(rset.getString("DesignationName"));
                            txtrptmanager.setText(rset.getString("ReportingManager"));
            
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPrevActionPerformed

   
    public void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desgnation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desgnation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desgnation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desgnation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Desgnation().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnsave;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtrptmanager;
    // End of variables declaration//GEN-END:variables
}
