/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author DEETH
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        setTitle("Employee Page");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuhome = new javax.swing.JMenu();
        jMenusalary = new javax.swing.JMenu();
        jMenuItemsalary = new javax.swing.JMenuItem();
        jMenumyaccount = new javax.swing.JMenu();
        jMenuItempersonal = new javax.swing.JMenuItem();
        jMenuItemEducation = new javax.swing.JMenuItem();
        jMenuItemwkexp = new javax.swing.JMenuItem();
        jMenuItemlogout = new javax.swing.JMenuItem();
        jMenugrief = new javax.swing.JMenu();
        jMenuItemgrf = new javax.swing.JMenuItem();
        aboutUs = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\MOVIES\\PICS\\9.jpg")); // NOI18N
        jLabel1.setText("WELCOME DEAR VALUED EMPLOYEE!!!!!");

        jMenuhome.setText("Home");
        jMenuBar1.add(jMenuhome);

        jMenusalary.setText("MySalary");

        jMenuItemsalary.setText("Details");
        jMenuItemsalary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemsalaryActionPerformed(evt);
            }
        });
        jMenusalary.add(jMenuItemsalary);

        jMenuBar1.add(jMenusalary);

        jMenumyaccount.setText("MyAccount");

        jMenuItempersonal.setText("Personal data");
        jMenuItempersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItempersonalActionPerformed(evt);
            }
        });
        jMenumyaccount.add(jMenuItempersonal);

        jMenuItemEducation.setText("Education Details");
        jMenuItemEducation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEducationActionPerformed(evt);
            }
        });
        jMenumyaccount.add(jMenuItemEducation);

        jMenuItemwkexp.setText("Work Experience");
        jMenuItemwkexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemwkexpActionPerformed(evt);
            }
        });
        jMenumyaccount.add(jMenuItemwkexp);

        jMenuItemlogout.setText("Logout");
        jMenuItemlogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemlogoutMouseClicked(evt);
            }
        });
        jMenuItemlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemlogoutActionPerformed(evt);
                LOGOUT(evt);
            }
        });
        jMenumyaccount.add(jMenuItemlogout);

        jMenuBar1.add(jMenumyaccount);

        jMenugrief.setText("Grief");

        jMenuItemgrf.setText("Add Complaint");
        jMenuItemgrf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemgrfActionPerformed(evt);
            }
        });
        jMenugrief.add(jMenuItemgrf);

        jMenuBar1.add(jMenugrief);

        aboutUs.setText("AboutUs");

        jMenuItem3.setText("CompanyDetails");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        aboutUs.add(jMenuItem3);

        jMenuBar1.add(aboutUs);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemsalaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemsalaryActionPerformed
        // TODO add your handling code here:
        Salary sal = new Salary();
        sal.Main();
    }//GEN-LAST:event_jMenuItemsalaryActionPerformed

    private void jMenuItempersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempersonalActionPerformed
        // TODO add your handling code here:
        PersonalData data = new PersonalData();
        data.Main();
    }//GEN-LAST:event_jMenuItempersonalActionPerformed

    private void jMenuItemEducationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEducationActionPerformed
        // TODO add your handling code here:
        EducationDetails educ = new EducationDetails();
        educ.Main();
    }//GEN-LAST:event_jMenuItemEducationActionPerformed

    private void jMenuItemwkexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemwkexpActionPerformed
        // TODO add your handling code here:
        WorkExperience wk = new  WorkExperience();
        wk.Main();
    }//GEN-LAST:event_jMenuItemwkexpActionPerformed

    private void jMenuItemgrfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemgrfActionPerformed
        // TODO add your handling code here:
        Grief grf = new Grief();
        grf.Main();
    }//GEN-LAST:event_jMenuItemgrfActionPerformed

    private void jMenuItemlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemlogoutActionPerformed
        // TODO add your handling code here:
         int option = JOptionPane.showConfirmDialog(null, "Are you sure you want to logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (option == JOptionPane.YES_OPTION) {
            dispose(); // close the current window
            System.exit(0); // exit the application
        }
    
        
        
    }//GEN-LAST:event_jMenuItemlogoutActionPerformed

    private void jMenuItemlogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemlogoutMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenuItemlogoutMouseClicked

    private void LOGOUT(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUT
        // TODO add your handling code here:
    }//GEN-LAST:event_LOGOUT

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         AboutUs us = new AboutUs();
        us.Main();
    }//GEN-LAST:event_jMenuItem3ActionPerformed
     
   
    public void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Employee().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu aboutUs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItemEducation;
    private javax.swing.JMenuItem jMenuItemgrf;
    private javax.swing.JMenuItem jMenuItemlogout;
    private javax.swing.JMenuItem jMenuItempersonal;
    private javax.swing.JMenuItem jMenuItemsalary;
    private javax.swing.JMenuItem jMenuItemwkexp;
    private javax.swing.JMenu jMenugrief;
    private javax.swing.JMenu jMenuhome;
    private javax.swing.JMenu jMenumyaccount;
    private javax.swing.JMenu jMenusalary;
    // End of variables declaration//GEN-END:variables
}
