/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JTextField;

/**
 *
 * @author DEETH
 */
public class LeaveForm extends javax.swing.JFrame {
     Connection con;
    PreparedStatement Statement;
    Statement st;
    String cs;
    String user;
    String password;
    String query;
    ResultSet rset;
    String records;
    
    String s1;
    String s2 ;
    String s3 ;
    String s4;
    String s5;
    String s6;

    /**
     * Creates new form LeaveForm
     */
    public LeaveForm() {
        setTitle("Leave Form");
        initComponents();
    }

    LeaveForm(String leave_Form) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblid = new javax.swing.JLabel();
        lblltype = new javax.swing.JLabel();
        lbllstatus = new javax.swing.JLabel();
        lblsdate = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        jComboBoxltype = new javax.swing.JComboBox();
        jComboBoxlstatus = new javax.swing.JComboBox();
        lbledate = new javax.swing.JLabel();
        btnsubmit = new javax.swing.JButton();
        sDate = new com.toedter.calendar.JDateChooser();
        eDate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        txtreason = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Leave Information");

        lblid.setText("ID:");

        lblltype.setText("Leave Type:");

        lbllstatus.setText("Leave Status:");

        lblsdate.setText("Start Date:");

        txtid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidActionPerformed(evt);
            }
        });

        jComboBoxltype.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Paid", "Not Paid" }));
        jComboBoxltype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxltypeActionPerformed(evt);
            }
        });

        jComboBoxlstatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Approved", "Rejected" }));

        lbledate.setText("End Date:");

        btnsubmit.setBackground(new java.awt.Color(0, 255, 255));
        btnsubmit.setText("SUBMIT");
        btnsubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubmitActionPerformed(evt);
            }
        });

        sDate.setDateFormatString("dd-MM-yyyy");

        eDate.setDateFormatString("dd-MM-yyyy");

        jLabel2.setText("Reason");

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrev.setText("PEVIOUS");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbllstatus)
                            .addComponent(lblid, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblltype)
                            .addComponent(lblsdate)
                            .addComponent(jLabel2)
                            .addComponent(lbledate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sDate, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(eDate, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtid, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtreason, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                            .addComponent(jComboBoxlstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDelete)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnsubmit)))
                        .addGap(141, 141, 141)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPrev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNext, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(sDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblid)
                                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblltype)
                                    .addComponent(jComboBoxltype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbllstatus)
                                    .addComponent(jComboBoxlstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(txtreason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(61, 61, 61)
                                .addComponent(lblsdate)))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbledate)
                            .addComponent(eDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEdit)
                            .addComponent(btnsubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnPrev))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxltypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxltypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxltypeActionPerformed

    private void btnsubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubmitActionPerformed
        // TODO add your handling code here:                                                                                   
    s1 = txtid.getText();
    s2 = jComboBoxltype.getSelectedItem().toString();
    s3 = jComboBoxlstatus.getSelectedItem().toString();
    s4 = txtreason.getText();
    s5 = ((JTextField) sDate.getDateEditor().getUiComponent()).getText();
    s6 = ((JTextField) eDate.getDateEditor().getUiComponent()).getText();
        
    try {
        Class.forName("com.mysql.jdbc.Driver");
        con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
        st = con.createStatement();
        query = "INSERT INTO `leaveinfo`(`ID`, `LeaveType`, `LeaveStatus`, `Reason`, `StartDate`, `EndDate`) VALUES ('" + s1 + "','" + s2 + "','" + s3 + "','" + s4 + "','" + s5 + "','" + s6 + "');";
        st.executeUpdate(query);
        
        JOptionPane.showMessageDialog(null, "Leave Information saved Successfully");
        st.close();
        con.close();
    } catch (ClassNotFoundException | SQLException | HeadlessException ex) {
        System.out.println(ex);
    }   


    }//GEN-LAST:event_btnsubmitActionPerformed

    private void txtidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
                
        int answer = JOptionPane.showConfirmDialog(this,"Are you sure You want to delete This Record?" ,"Confirm",JOptionPane.YES_NO_OPTION);
       
       if(answer == YES_OPTION){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
                st = con.createStatement();
                query = "DELETE FROM leaveinfo WHERE ID = '" +s1+"'";
                 st.executeUpdate(query);
                 
                 txtid.requestFocus();
                 
                 if(st.executeUpdate(query)==0){
                     JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Deleted");
                 }else{JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Doesnot Exist");}
                 }
                catch (SQLException | ClassNotFoundException ex){
                }
           
           finally{
               try{
                   if(st !=null){
                       st.close();}
                   if(con !=null){
                       con.close();
                   }
               }
               catch(SQLException ex){
                           }
                   
               }
           
       }
       else if (answer == NO_OPTION){
                   txtid.requestFocus();}
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        s2=jComboBoxltype.getSelectedItem().toString();
        s3=jComboBoxlstatus.getSelectedItem().toString();
        s4 = txtreason.getText();
        s5 = ((JTextField) sDate.getDateEditor().getUiComponent()).getText();
        s6 = ((JTextField) eDate.getDateEditor().getUiComponent()).getText();
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "UPDATE leaveinfo SET LeaveType = '" +s2+ "', LeaveStatus  = '" +s3+ "', Reason = '" +s4 +"',StartDate = '" +s5 +"', EndDate = '" +s6 +"'  WHERE ID ='"+s1+"'";
            int updated = st.executeUpdate(query);
            if (updated==1){
                JOptionPane.showMessageDialog(null, "Record edited");
            }
            rset.close();
            st.close();
            con.close();
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "SELECT * FROM leaveinfo WHERE ID = '"+s1 + "'";
           
            rset = st.executeQuery(query);
            if(rset.next()){
            
            txtid.setText(rset.getString("ID"));
            jComboBoxltype.setSelectedItem(rset.getString("LeaveType"));
            jComboBoxlstatus.setSelectedItem(rset.getString("LeaveType"));
            txtreason.setText(rset.getString("Reason"));
            String dDate = rset.getString("StartDate");
           ((JTextField) sDate.getDateEditor().getUiComponent()).setText(dDate);
           
            String dDate2 = rset.getString("EndDate");
            ((JTextField) eDate.getDateEditor().getUiComponent()).setText(dDate2);
            
            JOptionPane.showMessageDialog(null,"Record found");}
            else{
                JOptionPane.showMessageDialog(null,"Record Not found");
            rset.close();
            st.close();
            con.close();}
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
            
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM leaveinfo");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.next()){
                            txtid.setText(rset.getString("ID"));
                            jComboBoxltype.setSelectedItem(rset.getString("LeaveType"));
                            jComboBoxlstatus.setSelectedItem(rset.getString("LeaveType"));
                            txtreason.setText(rset.getString("Reason"));
                            String dDate = rset.getString("StartDate");
                            ((JTextField) sDate.getDateEditor().getUiComponent()).setText(dDate);
           
                            String dDate2 = rset.getString("EndDate");
                            ((JTextField) eDate.getDateEditor().getUiComponent()).setText(dDate2);
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
            
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM leaveinfo");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.previous()){
                            txtid.setText(rset.getString("ID"));
                            jComboBoxltype.setSelectedItem(rset.getString("LeaveType"));
                            jComboBoxlstatus.setSelectedItem(rset.getString("LeaveType"));
                            txtreason.setText(rset.getString("Reason"));
                            String dDate = rset.getString("StartDate");
                            ((JTextField) sDate.getDateEditor().getUiComponent()).setText(dDate);
           
                            String dDate2 = rset.getString("EndDate");
                            ((JTextField) eDate.getDateEditor().getUiComponent()).setText(dDate2);
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPrevActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeaveForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new LeaveForm().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnsubmit;
    private com.toedter.calendar.JDateChooser eDate;
    private javax.swing.JComboBox jComboBoxlstatus;
    private javax.swing.JComboBox jComboBoxltype;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lbledate;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lbllstatus;
    private javax.swing.JLabel lblltype;
    private javax.swing.JLabel lblsdate;
    private com.toedter.calendar.JDateChooser sDate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtreason;
    // End of variables declaration//GEN-END:variables
}
