/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import java.lang.NullPointerException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.AbstractTableModel;
import static java.lang.Class.forName;
import java.util.jar.Attributes.Name;
import javax.swing.JTextField;

/**
 *
 * @author DEETH
 */
public class NewEmployee extends javax.swing.JFrame {
     Connection con;
    PreparedStatement Statement;
    Statement st;
    String cs;
    String user;
    String password;
    String query;
    ResultSet rset;
    String records;
    String s1;
    String s2 ;
    String s3 ;
    String s4;
    String s5;
    String s6;
    String s7;
    String s8;
    String s9 ;
    String s10;
      
    
    
    
    File selectedImageFile ;
    

    /**
     * Creates new form NewEmployee
     * @param Title
     */
    public NewEmployee(String Title) {
       
         con= null;
        st=null;
        Statement = null;
        cs = "jdbc:mysql://localhost:3306/hr_mgt_system";
        user = "root";
        password="";
        setTitle("New Employee Registeration");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        JLabelID = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabelgender = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelphone = new javax.swing.JLabel();
        jLabeldesignation = new javax.swing.JLabel();
        jLabeljoining = new javax.swing.JLabel();
        jLabeladdress = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jTextAddress = new javax.swing.JTextField();
        jTextEmail = new javax.swing.JTextField();
        jTextPhone = new javax.swing.JTextField();
        jTextDesignation = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButtonadd = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        date = new com.toedter.calendar.JDateChooser();
        jButtonEdit = new javax.swing.JButton();
        jButtonFind = new javax.swing.JButton();
        jButtonFirst = new javax.swing.JButton();
        jButtonLast = new javax.swing.JButton();
        jButtonNext = new javax.swing.JButton();
        jButtonPrevious = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jImage = new javax.swing.JPanel();
        jImage1 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        lblImage = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnImage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        JLabelID.setText("ID:");

        jLabelName.setText("Name:");

        jLabelgender.setText("Gender:");

        jLabelDOB.setText("DateofBirth:");

        jLabelemail.setText("Email:");

        jLabelphone.setText("PhoneNo.:");

        jLabeldesignation.setText("Designation:");

        jLabeljoining.setText("DateOfJoining:");

        jLabeladdress.setText("Address:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Male", "Female" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButtonadd.setBackground(new java.awt.Color(0, 255, 255));
        jButtonadd.setText("Add Employee");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Employee Registration Form");

        date.setDateFormatString("dd-MM-yyyy");

        jButtonEdit.setText("EDIT");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonFind.setText("FIND");
        jButtonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFindActionPerformed(evt);
            }
        });

        jButtonFirst.setText("FIRST");
        jButtonFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFirstActionPerformed(evt);
            }
        });

        jButtonLast.setText("LAST");
        jButtonLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLastActionPerformed(evt);
            }
        });

        jButtonNext.setText("NEXT");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("PREVIOUS");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jButtonDelete.setText("DELETE");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jImageLayout = new javax.swing.GroupLayout(jImage);
        jImage.setLayout(jImageLayout);
        jImageLayout.setHorizontalGroup(
            jImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jImageLayout.setVerticalGroup(
            jImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jImage1, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        jdate.setDateFormatString("dd-MM-yyyy");

        jLabel1.setText("PHOTO");

        btnImage.setText("BROWSE IMAGE");
        btnImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelgender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(65, 65, 65))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JLabelID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(99, 99, 99)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextName, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addComponent(jTextID)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEdit)
                            .addComponent(jButtonDelete))
                        .addGap(148, 148, 148))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDOB)
                            .addComponent(jLabeladdress)
                            .addComponent(jLabelemail))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextEmail)
                            .addComponent(jTextAddress)
                            .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelphone)
                            .addComponent(jLabeldesignation)
                            .addComponent(jLabeljoining))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(279, 279, 279))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(336, 336, 336))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonFind, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnImage, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(116, 116, 116)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonPrevious)
                                    .addComponent(jButtonNext, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(104, 104, 104))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonFirst)
                    .addComponent(jButtonLast))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLabelID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jLabelName))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelgender)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(65, 65, 65))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelphone)
                                .addComponent(jLabelDOB))))
                    .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabeldesignation)
                        .addComponent(jLabeladdress)
                        .addComponent(jTextAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabelemail)
                                .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabeljoining)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonFirst)
                                    .addComponent(jButtonEdit)
                                    .addComponent(jButtonNext)
                                    .addComponent(btnImage))
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonadd, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonLast)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonFind)
                            .addComponent(jButtonPrevious))
                        .addGap(17, 17, 17))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
        s2 =jTextName.getText();
        s3 =jComboBox1.getSelectedItem().toString();
        s4 = ((JTextField) date.getDateEditor().getUiComponent()).getText();
        s5 =jTextAddress.getText();
        s6 =jTextPhone.getText();
        s7 =jTextEmail.getText();
        s8 =jTextDesignation.getText();
        s9 = ((JTextField) jdate.getDateEditor().getUiComponent()).getText();
        s10 = selectedImageFile.toString().replace("\\", "\\\\");
      
        
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query="INSERT INTO `employeeinfo`(`ID`, `Name`, `Gender`, `DateOfBirth`, `Address`, `Phone`, `Email`, `Designation`, `DateOfJoining`, `photo`) VALUES ('" +s1+"','"+s2+"','"+s3+"','" +s4+"','" +s5+"','" +s6+"','" +s7+"','" +s8+"','" +s9+"','" +s10+"');";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"Employee Record saved Successfully");
            st.close();
            con.close();}
        
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
                System.out.println(ex);
        }   
        
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtonFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFirstActionPerformed
        // TODO add your handling code here:
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeinfo");
            
            rset = st.executeQuery(query);
            if(rset.first()){
            jTextID.setText(rset.getString("ID"));
            jTextName.setText(rset.getString("Name"));
            jComboBox1.setSelectedItem(rset.getString("Gender"));
            String dDate = rset.getString("DateOfBirth");
            ((JTextField) date.getDateEditor().getUiComponent()).setText(dDate);
            jTextAddress.setText(rset.getString("Address"));
            jTextPhone.setText(rset.getString("Phone"));
            jTextEmail.setText(rset.getString("Email"));
            jTextDesignation.setText(rset.getString("Designation"));
            String dDate1 = rset.getString("DateOfJoining");
            ((JTextField) jdate.getDateEditor().getUiComponent()).setText(dDate1);
            
            String limage = rset.getString("photo");
            ImageIcon ii = new ImageIcon(limage );
            
            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
            jImage1.setIcon(new ImageIcon(i));
            
            
            
            
            }
            else{
                JOptionPane.showMessageDialog(null,"No Record Found");
                
            }
            JOptionPane.showMessageDialog(null, "Record Found");
            rset.close();
            st.close();
            con.close();
            
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonFirstActionPerformed

    private void jButtonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFindActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
        
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
           query = "SELECT * FROM employeeinfo WHERE ID = '"+s1 + "'";
           
            rset = st.executeQuery(query);
            if(rset.next()){
            
            jTextName.setText(rset.getString("Name"));
            jComboBox1.setSelectedItem(rset.getString("Gender"));
            String dDate = rset.getString("DateOfBirth");
            ((JTextField) date.getDateEditor().getUiComponent()).setText(dDate);
            jTextAddress.setText(rset.getString("Address"));
            jTextPhone.setText(rset.getString("Phone"));
            jTextEmail.setText(rset.getString("Email"));
            jTextDesignation.setText(rset.getString("Designation"));
            String dDate1 = rset.getString("DateOfJoining");
            ((JTextField) jdate.getDateEditor().getUiComponent()).setText(dDate1);
            String limage = rset.getString("photo");
            ImageIcon ii = new ImageIcon(limage );
            
            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
            jImage1.setIcon(new ImageIcon(i));
            
            JOptionPane.showMessageDialog(null,"Record found");}
            else{
                JOptionPane.showMessageDialog(null,"Record Not found");
            rset.close();
            st.close();
            con.close();}
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonFindActionPerformed

    private void jButtonLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLastActionPerformed
        // TODO add your handling code here:
        
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeinfo");
            
            rset = st.executeQuery(query);
            if(rset.last()){
            jTextID.setText(rset.getString("ID"));
            jTextName.setText(rset.getString("Name"));
            jComboBox1.setSelectedItem(rset.getString("Gender"));
            String dDate = rset.getString("DateOfBirth");
            ((JTextField) date.getDateEditor().getUiComponent()).setText(dDate);
          
            jTextAddress.setText(rset.getString("Address"));
            jTextPhone.setText(rset.getString("Phone"));
            jTextEmail.setText(rset.getString("Email"));
            jTextDesignation.setText(rset.getString("Designation"));
            String dDate1 = rset.getString("DateOfJoining");
            ((JTextField) jdate.getDateEditor().getUiComponent()).setText(dDate1);
            String limage = rset.getString("photo");
            ImageIcon ii = new ImageIcon(limage );
            
            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
            jImage1.setIcon(new ImageIcon(i));
            
            
            }
            else{
                JOptionPane.showMessageDialog(null,"No Record Found");
                
            }
            JOptionPane.showMessageDialog(null, "Record Found");
            rset.close();
            st.close();
            con.close();
            
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
           
    }//GEN-LAST:event_jButtonLastActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
        s2 =jTextName.getText();
        s3 =jComboBox1.getSelectedItem().toString();
        s4 = ((JTextField) date.getDateEditor().getUiComponent()).getText();
        s5 =jTextAddress.getText();
        s6 =jTextPhone.getText();
        s7 =jTextEmail.getText();
        s8 =jTextDesignation.getText();
        s9 = ((JTextField) jdate.getDateEditor().getUiComponent()).getText();
        s10 = selectedImageFile.toString().replace("\\", "\\\\");
        
         try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "UPDATE employeeinfo SET Name = '" +s2 +"', Gender = '" +s3 +"', DateOfBirth = '" +s4 +"', Address = '" +s5+"', Phone = '" +s6+"', Email = '" +s7+ "', Designation = '" +s8+"', DateOfJoining = '" +s9+"', photo = '" +s10+"' WHERE ID ='"+s1+"'";
            int updated = st.executeUpdate(query);
            if (updated==1){
                JOptionPane.showMessageDialog(null, "Record edited");
            }
            rset.close();
            st.close();
            con.close();
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
       
        
       int answer = JOptionPane.showConfirmDialog(this,"Are you sure You want to delete This Record?" ,"Confirm",JOptionPane.YES_NO_OPTION);
       
       if(answer == YES_OPTION){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
                st = con.createStatement();
                query = "DELETE FROM employeeinfo WHERE ID = '" +s1+"'";
                 st.executeUpdate(query);
                 
                 jTextID.requestFocus();
                 
                 if(st.executeUpdate(query)==0){
                     JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Deleted");
                 }else{JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Doesnot Exist");}
                 }
                catch (SQLException | ClassNotFoundException ex){
                }
           
           finally{
               try{
                   if(st !=null){
                       st.close();}
                   if(con !=null){
                       con.close();
                   }
               }
               catch(SQLException ex){
                           }
                   
               }
           
       }
       else if (answer == NO_OPTION){
                   jTextID.requestFocus();}
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeinfo");
           
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.next()){
                            jTextID.setText(rset.getString("ID"));
                            jTextName.setText(rset.getString("Name"));
                            jComboBox1.setSelectedItem(rset.getString("Gender"));
                            String dDate = rset.getString("DateOfBirth");
                            ((JTextField) date.getDateEditor().getUiComponent()).setText(dDate);
                            jTextAddress.setText(rset.getString("Address"));
                            jTextPhone.setText(rset.getString("Phone"));
                            jTextEmail.setText(rset.getString("Email"));
                            jTextDesignation.setText(rset.getString("Designation"));
                            String dDate1 = rset.getString("DateOfJoining");
                            ((JTextField) jdate.getDateEditor().getUiComponent()).setText(dDate1);
                            String limage = rset.getString("photo");
                            ImageIcon ii = new ImageIcon(limage );
            
                            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
                            jImage1.setIcon(new ImageIcon(i));
          
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        // TODO add your handling code here:
        s1=jTextID.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeinfo");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.previous()){
                            jTextID.setText(rset.getString("ID"));
                            jTextName.setText(rset.getString("Name"));
                            jComboBox1.setSelectedItem(rset.getString("Gender"));
                            String dDate = rset.getString("DateOfBirth");
                            ((JTextField) date.getDateEditor().getUiComponent()).setText(dDate);
          
                            jTextAddress.setText(rset.getString("Address"));
                            jTextPhone.setText(rset.getString("Phone"));
                            jTextEmail.setText(rset.getString("Email"));
                            jTextDesignation.setText(rset.getString("Designation"));
                            String dDate1 = rset.getString("DateOfJoining");
                            ((JTextField) jdate.getDateEditor().getUiComponent()).setText(dDate1);
                            String limage = rset.getString("photo");
                            ImageIcon ii = new ImageIcon(limage );
            
                            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
                            jImage1.setIcon(new ImageIcon(i));
          
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void btnImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImageActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        FileNameExtensionFilter fner = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg"); 
        browseImageFile.addChoosableFileFilter(fner);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
        
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            
            ImageIcon ii = new ImageIcon(selectedImagePath );
            
            Image i = ii.getImage().getScaledInstance(jImage1.getWidth(), jImage1.getHeight(), Image.SCALE_SMOOTH);
            jImage1.setIcon(new ImageIcon(i));
        }
    }//GEN-LAST:event_btnImageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewEmployee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelID;
    private javax.swing.JButton btnImage;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JButton jButtonFind;
    private javax.swing.JButton jButtonFirst;
    private javax.swing.JButton jButtonLast;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JComboBox jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JPanel jImage;
    private javax.swing.JLabel jImage1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabeladdress;
    private javax.swing.JLabel jLabeldesignation;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelgender;
    private javax.swing.JLabel jLabeljoining;
    private javax.swing.JLabel jLabelphone;
    private javax.swing.JTextField jTextAddress;
    private javax.swing.JTextField jTextDesignation;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextPhone;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lblImage;
    // End of variables declaration//GEN-END:variables
}
