/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mypackage;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.NO_OPTION;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.JTextField;

/**
 *
 * @author DEETH
 */
public class Performance extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement Statement;
    Statement st;
    String cs;
    String user;
    String password;
    String query;
    ResultSet rset;
    String records;
    
    String s1;
    String s2;
    String s3;
    String s4;
    String s5;
    String s6;
    String s7;
        

    /**
     * Creates new form Performance
     */
    public Performance() {
        setTitle("Employee Perfomance");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabelid = new javax.swing.JLabel();
        jLabelrvPeriod = new javax.swing.JLabel();
        jLabelrvName = new javax.swing.JLabel();
        jLabelrating = new javax.swing.JLabel();
        jLabelfeedback = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtrvName = new javax.swing.JTextField();
        jComboBoxrating = new javax.swing.JComboBox();
        jButtonSubmit = new javax.swing.JButton();
        jComboBoxfeedback = new javax.swing.JComboBox();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        sdate = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Employee Performance Records");
        jLabel1.setToolTipText("");

        jLabelid.setText("ID:");

        jLabelrvPeriod.setText("ReviewPeriod:");

        jLabelrvName.setText("ReviewerName:");

        jLabelrating.setText("Rating:");

        jLabelfeedback.setText("FeedBack:");

        jComboBoxrating.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Excellent", "Good", "Poor", "Very Poor" }));

        jButtonSubmit.setBackground(new java.awt.Color(0, 255, 255));
        jButtonSubmit.setText("SUBMIT");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });

        jComboBoxfeedback.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Improved", "Maintained", "Declined", " " }));

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setText("FIND");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnNext.setText("NEXT");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setText("PREVIOUS");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        sdate.setDateFormatString("dd-MM-yyyy");

        jLabel2.setText("FROM:");

        jLabel3.setText("TO:");

        edate.setDateFormatString("dd-MM-yyyy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelrvName)
                    .addComponent(jLabelrating, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelfeedback, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelrvPeriod, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(308, 308, 308)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(sdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtrvName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxrating, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxfeedback, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnDelete)
                .addGap(49, 49, 49)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSubmit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnNext)
                .addGap(69, 69, 69)
                .addComponent(btnPrevious)
                .addGap(56, 56, 56))
            .addGroup(layout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelid))
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(edate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelrvPeriod)
                                    .addComponent(jLabel2))
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtrvName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelrvName))
                        .addGap(62, 62, 62)
                        .addComponent(jLabelrating))
                    .addComponent(jComboBoxrating, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelfeedback)
                    .addComponent(jComboBoxfeedback, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnFind)
                    .addComponent(btnEdit)
                    .addComponent(btnNext)
                    .addComponent(btnPrevious))
                .addGap(43, 43, 43))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        // TODO add your handling code here:
        
        s1=txtid.getText();
        s2 = ((JTextField) sdate.getDateEditor().getUiComponent()).getText();
        s3 = ((JTextField) edate.getDateEditor().getUiComponent()).getText();
        s4 =txtrvName.getText();
        s5 =jComboBoxrating.getSelectedItem().toString();
        s6 =jComboBoxfeedback.getSelectedItem().toString();
        
        s7 = s2 + " - " + s3;

       
             
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query="INSERT INTO `employeeperformance`(`ID`, `ReviewPeriod`, `ReviewerName`, `Rating`, `Feedback`) VALUES('" +s1+"','" +s7+"','" +s4+"','" +s5+"','" +s6+"');";
            st.executeUpdate(query);
            JOptionPane.showMessageDialog(null,"New Performance added Successfully");
            st.close();
            con.close();}
        
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
                System.out.println(ex);
        }   
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        
        s1=txtid.getText();
               
        int answer = JOptionPane.showConfirmDialog(this,"Are you sure You want to delete This Record?" ,"Confirm",JOptionPane.YES_NO_OPTION);
       
       if(answer == YES_OPTION){
           try{
               Class.forName("com.mysql.jdbc.Driver");
                 con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
                 st = con.createStatement();
                 query = "DELETE FROM employeeperformance WHERE ID = '" +s1+"'";
                 st.executeUpdate(query);
                 
                 txtid.requestFocus();
                 
                 if(st.executeUpdate(query)==0){
                     JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Deleted");
                 }else{JOptionPane.showMessageDialog(null,"Record with ID: '"+s1+"' Doesnot Exist");}
                 }
                catch (SQLException | ClassNotFoundException ex){
                }
           
           finally{
               if(st !=null){
                   try {
                       st.close();
                   } catch (SQLException ex) {
                       Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
                   }
}
               if(con !=null){
                   try {
                       con.close();
                   } catch (SQLException ex) {
                       Logger.getLogger(Performance.class.getName()).log(Level.SEVERE, null, ex);
                   }
               }

               }
           
       }
       else if (answer == NO_OPTION){
                   txtid.requestFocus();}
                                             
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        s2 = ((JTextField) sdate.getDateEditor().getUiComponent()).getText();
        s3 = ((JTextField) edate.getDateEditor().getUiComponent()).getText();
        s4 =txtrvName.getText();
        s5 =jComboBoxrating.getSelectedItem().toString();
        s6 =jComboBoxfeedback.getSelectedItem().toString();
        
        s7 = s2 + " - " + s3;

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "UPDATE employeeperformance SET ReviewPeriod = '" +s7+ "', ReviewerName  = '" +s4+ "', Rating = '" +s5 +"',Feedback = '" +s6 +"'  WHERE ID ='"+s1+"'";
            int updated = st.executeUpdate(query);
            if (updated==1){
                JOptionPane.showMessageDialog(null, "Record edited");
            }
            rset.close();
            st.close();
            con.close();
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
                   
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = "SELECT * FROM employeeperformance WHERE ID = '"+s1 + "'";
           
            rset = st.executeQuery(query);
            if(rset.next()){
            
            txtid.setText(rset.getString("ID"));
            String dDate = rset.getString("StartDate");
            ((JTextField) sdate.getDateEditor().getUiComponent()).setText(dDate);
          
            String dDate1 = rset.getString("EndDate");
            ((JTextField) edate.getDateEditor().getUiComponent()).setText(dDate1);
          
            txtrvName.setText(rset.getString("ReviewerName"));
            jComboBoxrating.setSelectedItem(rset.getString("Rating"));
            jComboBoxfeedback.setSelectedItem(rset.getString("Feedback"));
            
            JOptionPane.showMessageDialog(null,"Record found");}
            else{
                JOptionPane.showMessageDialog(null,"Record Not found");
            rset.close();
            st.close();
            con.close();}
        }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
                
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeperformance");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.previous()){
                            txtid.setText(rset.getString("ID"));
                            String dDate = rset.getString("StartDate");
                            ((JTextField) sdate.getDateEditor().getUiComponent()).setText(dDate);
          
                            String dDate1 = rset.getString("EndDate");
                            ((JTextField) edate.getDateEditor().getUiComponent()).setText(dDate1);
          
                            txtrvName.setText(rset.getString("ReviewerName"));
                            jComboBoxrating.setSelectedItem(rset.getString("Rating"));
                            jComboBoxfeedback.setSelectedItem(rset.getString("Feedback"));
                            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        s1=txtid.getText();
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/hr_mgt_system", "root", "");
            st = con.createStatement();
            query = ("SELECT * FROM employeeperformance");
            
            rset = st.executeQuery(query);
            
            while(true){
                if(rset.next()){
                    if(rset.getString("ID").equals(s1)){
                        if(rset.next()){
                            txtid.setText(rset.getString("ID"));
                            String dDate = rset.getString("StartDate");
                            ((JTextField) sdate.getDateEditor().getUiComponent()).setText(dDate);
          
                            String dDate1 = rset.getString("EndDate");
                            ((JTextField) edate.getDateEditor().getUiComponent()).setText(dDate1);
          
                            txtrvName.setText(rset.getString("ReviewerName"));
                            jComboBoxrating.setSelectedItem(rset.getString("Rating"));
                            jComboBoxfeedback.setSelectedItem(rset.getString("Feedback"));
            
                            break;
                        }
                        else{
                            JOptionPane.showMessageDialog(null,"No more record found" );
                            break;
                        }
                        }
                    }
                       
                }
            rset.close();
            st.close();
            con.close();
            
            }
        catch(ClassNotFoundException | SQLException | HeadlessException ex){
            System.out.println(ex);
        }
    }//GEN-LAST:event_btnNextActionPerformed
public void Main() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Performance().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private com.toedter.calendar.JDateChooser edate;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JComboBox jComboBoxfeedback;
    private javax.swing.JComboBox jComboBoxrating;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelfeedback;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabelrating;
    private javax.swing.JLabel jLabelrvName;
    private javax.swing.JLabel jLabelrvPeriod;
    private com.toedter.calendar.JDateChooser sdate;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtrvName;
    // End of variables declaration//GEN-END:variables
}
